name: SfM_RF
channels:
  - conda-forge
  - defaults
dependencies:
  - affine=2.4.0
  - asttokens=2.4.0
  - attrs=23.1.0
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.5
  - blas=1.0
  - blas-devel=3.9.0
  - blosc=1.21.5
  - branca=0.7.0
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - ca-certificates=2023.11.17
  - cairo=1.18.0
  - ceres-solver=2.1.0
  - certifi=2023.11.17
  - cffi=1.16.0
  - cfitsio=4.3.0
  - charset-normalizer=3.3.2
  - click=8.1.7
  - click-plugins=1.1.1
  - cligj=0.7.2
  - colorama=0.4.6
  - comm=0.1.4
  - contourpy=1.2.0
  - coverage=7.4.0
  - curl=8.4.0
  - cycler=0.12.1
  - debugpy=1.8.0
  - decorator=5.1.1
  - draco=1.5.6
  - eigen=3.4.0
  - exceptiongroup=1.1.3
  - executing=1.2.0
  - exiv2=0.27.6
  - expat=2.5.0
  - filelock=3.13.1
  - fiona=1.9.5
  - folium=0.15.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.45.1
  - freetype=2.12.1
  - freexl=2.0.0
  - future=0.18.3
  - gdal=3.7.3
  - geopandas=0.14.1
  - geopandas-base=0.14.1
  - geos=3.12.0
  - geotiff=1.7.1
  - gettext=0.21.1
  - gflags=2.2.2
  - glib=2.78.1
  - glib-tools=2.78.1
  - glog=0.6.0
  - gsl=2.7
  - gst-plugins-base=1.22.7
  - gstreamer=1.22.7
  - hdf4=4.2.15
  - hdf5=1.14.2
  - httplib2=0.22.0
  - icu=73.2
  - idna=3.4
  - importlib-metadata=6.8.0
  - importlib_metadata=6.8.0
  - intel-openmp=2023.2.0
  - ipykernel=6.25.2
  - ipython=8.16.1
  - jedi=0.19.1
  - jinja2=3.1.2
  - joblib=1.3.2
  - jupyter_client=8.5.0
  - jupyter_core=5.5.0
  - kealib=1.5.2
  - khronos-opencl-icd-loader=2023.04.17
  - kiwisolver=1.4.5
  - krb5=1.21.2
  - laspy=2.3.0
  - laz-perf=3.4.0
  - lcms2=2.15
  - lerc=4.0.0
  - libabseil=20230802.1
  - libaec=1.1.2
  - libarchive=3.7.2
  - libblas=3.9.0
  - libboost-headers=1.82.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libclang=15.0.7
  - libclang13=15.0.7
  - libcurl=8.4.0
  - libdeflate=1.19
  - libexpat=2.5.0
  - libffi=3.4.2
  - libgdal=3.7.3
  - libglib=2.78.1
  - libhwloc=2.9.3
  - libiconv=1.17
  - libjpeg-turbo=3.0.0
  - libkml=1.3.0
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libnetcdf=4.9.2
  - libogg=1.3.4
  - libpng=1.6.39
  - libpq=16.1
  - libprotobuf=4.24.4
  - librttopo=1.1.0
  - libsodium=1.0.18
  - libspatialindex=1.9.3
  - libspatialite=5.1.0
  - libsqlite=3.44.2
  - libssh2=1.11.0
  - libtiff=4.6.0
  - libuv=1.44.2
  - libvorbis=1.3.7
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - libxcb=1.15
  - libxml2=2.11.6
  - libxslt=1.1.37
  - libzip=1.10.1
  - libzlib=1.2.13
  - lxml=4.9.3
  - lz4-c=1.9.4
  - lzo=2.10
  - m2w64-gcc-libgfortran=5.3.0
  - m2w64-gcc-libs=5.3.0
  - m2w64-gcc-libs-core=5.3.0
  - m2w64-gmp=6.1.0
  - m2w64-libwinpthread-git=5.0.0.4634.697f757
  - mapclassify=2.6.1
  - markupsafe=2.1.3
  - matplotlib-base=3.8.2
  - matplotlib-inline=0.1.6
  - minizip=4.0.1
  - mkl=2023.2.0
  - mkl-devel=2023.2.0
  - mkl-include=2023.2.0
  - mkl-service=2.4.0
  - mock=5.1.0
  - mpmath=1.3.0
  - msys2-conda-epoch=20160418
  - munch=4.0.0
  - munkres=1.1.4
  - nest-asyncio=1.5.8
  - networkx=3.2.1
  - ninja=1.11.1
  - nitro=2.7.dev8
  - nose2=0.9.2
  - numpy=1.26.2
  - openjpeg=2.5.0
  - openssl=3.2.0
  - owslib=0.29.3
  - packaging=23.2
  - pandas=2.1.3
  - parso=0.8.3
  - patsy=0.5.3
  - pcre2=10.42
  - pdal=2.6.0
  - pickleshare=0.7.5
  - pillow=10.1.0
  - pip=23.3.1
  - pixman=0.42.2
  - platformdirs=3.11.0
  - plotly=5.18.0
  - ply=3.11
  - poppler=23.11.0
  - poppler-data=0.4.12
  - postgresql=16.1
  - proj=9.3.0
  - prompt-toolkit=3.0.39
  - prompt_toolkit=3.0.39
  - psutil=5.9.5
  - psycopg2=2.9.9
  - pthread-stubs=0.4
  - pthreads-win32=2.9.1
  - pure_eval=0.2.2
  - pycparser=2.21
  - pygments=2.16.1
  - pykrige=1.7.1
  - pyntcloud=0.3.1
  - pyparsing=3.1.1
  - pyproj=3.6.1
  - pyqt=5.15.9
  - pyqt5-sip=12.12.2
  - pyqtwebkit=5.15.9
  - pysocks=1.7.1
  - python=3.11.6
  - python-dateutil=2.8.2
  - python-tzdata=2023.3
  - python_abi=3.11
  - pytorch=2.1.0
  - pytz=2023.3.post1
  - pywin32=306
  - pyyaml=6.0.1
  - pyzmq=25.1.1
  - qca=2.3.7
  - qgis=3.34.0
  - qjson=0.9.0
  - qscintilla2=2.14.1
  - qt-main=5.15.8
  - qtkeychain=0.14.2
  - qtwebkit=5.212
  - qwt=6.2.0
  - rasterio=1.3.9
  - remotior-sensus=0.3.5
  - requests=2.31.0
  - richdem=2.3.0
  - rtree=1.1.0
  - scikit-learn=1.3.2
  - scipy=1.11.4
  - seaborn=0.13.0
  - seaborn-base=0.13.0
  - setuptools=68.2.2
  - shapely=2.0.2
  - sip=6.7.12
  - six=1.16.0
  - snappy=1.1.10
  - snuggs=1.4.7
  - sqlite=3.44.2
  - stack_data=0.6.2
  - statsmodels=0.14.0
  - suitesparse=5.4.0
  - sympy=1.12
  - tbb=2021.10.0
  - tenacity=8.2.3
  - threadpoolctl=3.2.0
  - tiledb=2.16.3
  - tk=8.6.13
  - toml=0.10.2
  - tomli=2.0.1
  - tornado=6.3.3
  - traitlets=5.12.0
  - typing-extensions=4.8.0
  - typing_extensions=4.8.0
  - tzdata=2023c
  - ucrt=10.0.22621.0
  - uriparser=0.9.7
  - urllib3=2.1.0
  - vc=14.3
  - vc14_runtime=14.36.32532
  - vs2015_runtime=14.36.32532
  - wcwidth=0.2.8
  - wheel=0.41.2
  - win_inet_pton=1.1.0
  - xerces-c=3.2.4
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xyzservices=2023.10.1
  - xz=5.2.6
  - yaml=0.2.5
  - zeromq=4.3.5
  - zipp=3.17.0
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - cloudpickle==3.0.0
      - dask==2023.11.0
      - dask-glm==0.3.1
      - dask-ml==2023.3.24
      - distributed==2023.11.0
      - fsspec==2023.10.0
      - llvmlite==0.41.1
      - locket==1.0.0
      - msgpack==1.0.7
      - multipledispatch==1.0.0
      - numba==0.58.1
      - partd==1.4.1
      - sortedcontainers==2.4.0
      - sparse==0.14.0
      - tblib==3.0.0
      - toolz==0.12.0
      - zict==3.0.0

